### ISSUE TITLE
all recode.vcf removed

### ISSUE THREAD

**Issue by Enorya** [laczkol/RADOrgMiner#3]
Hello,

I am trying to use your script on my own data but I end up with an error message linked to the line 708 of your script:
`ls: cannot access '*.recode.vcf': No such file or directory`
I think it is linked to those line of your code:
```bash
find ./ -name "*.recode.vcf" -type f -exec awk -v x=$nrecode_comment -v y=$minlen 'NR==x+y{exit 1}' {} \; -exec echo rm {} \; > rmrecodevcf
if [[ $(wc -l <rmrecodevcf) -ge 1 ]]; then 
		sh rmrecodevcf &> /dev/null
		rm rmrecodevcf
	else
		rm rmrecodevcf
	fi
``` 
Indeed, after executing those lines all the recode.vcf files are removed hence the ls command can't find them.
I don't understand the goal of the line 699 and because of that I don't understand why all my recode.vcf files are deleted. 
I only have 2 recode.vcf files that are not empty so I assume those 2 should be kept at least, no?

Can you help me? Thank you

**Comment by laczkol** [comment]
Hello,
Thank you again for contacting me. Those lines are meant to filter for too short loci after filtering for missingness. My strategy is to filter all loci with vcftools and delete those `*recode.vcf` files containing less than a given number of sites with clumping of haplotypes disabled in freebayes. Removal of short loci is achieved by executing `rmrecodevcf`.  For example, using the dummy dataset with default value of `-minlen` (100) - that means loci shorter than 100 bp after filtering are not kept in the final dataset - I get 7 loci, but changing `-minlen` to 1000 reduces the final dataset to 4 loci. After setting this value higher than 1142 (the longest locus), I could reproduce your error.
My best guess for this issue is that your loci are too short after filtering for missingness. I don't know exactly your wet-lab protocol, but using 2bRAD or 100bp SE reads can yield in shorter loci than 100bp, so are filtered out by default in this pipeline. Another option might be a too strict threshold for the missingness value, which is set by default to 0.8 (a site can be absent in 20% of samples). If, for some reason, higher missingness can be expected on these loci, applying a more liberal filter might help to obtain the desired loci sequences. I have observed a similar but not so significant effect with this pipeline when analyzing distantly related species.
 You can change the mentioned values on the command line by setting the value of `-minlen` and `-miss`.
If you have unfiltered vcf files in the output directory, you can try to filter them manually for missingness, then counting the sites in the output should give you an idea about the length of loci.
Did you inspect the read depth distribution of your samples along the reference genome? That might also help assess the number/length/read depth of loci captured.
If the issue is indeed the length of individual loci, I could add a few lines of code to check for this problem and output a message to `stoud`.

**Comment by Enorya** [comment]
Hello,

Thank you for your quick answer!
I've just set the `-minlen` parameter to 50 and with this value I'm able to retrieve the 2 loci that were deleted before. You were right, they were too short (86 and 87 bases). I think it's a good idea to add few lines of code for this problem and output a message, it will help people in my case to understand their problem.

**Comment by laczkol** [comment]
Hello,
Thank you very much for your feedback! I implemented a quick check in the pipeline for the number of loci left after filtering for missingness and minimum length. If there are no loci left to process, the following message should appear:
````bash
There are no loci left to process after filtering for minimum locus length (-minlen 100) and missingness (-miss 0.8)
There is a chance that the analyzed dataset does not contain any organellar loci, or the -minlen, -miss or -mbc values were set incorrectly
Please check the results of the alignment step to set these parameters correctly
````
